# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Clustering
								 A QGIS plugin
 Receives polygon shapefile as input and applies clustering methods for the generation of choropleth maps 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
							  -------------------
		begin                : 2020-03-18
		git sha              : $Format:%H$
		copyright            : (C) 2020 by Prudencio T. and Maia B.
		email                : tiagoprudencio16@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

from ClusterMap.gui.CustomWidgets.hierarchicalWidget.hierarchicalWidget import hierarchicalWidget
from processing.gui.wrappers import WidgetWrapper

class hierarchicalWrapper(WidgetWrapper):
	def __init__(self, *args, **kwargs):
		super(hierarchicalWrapper, self).__init__(*args, **kwargs)

	
	def createPanel(self):
		return hierarchicalWidget()

	def createWidget(self):
		self.panel = self.createPanel()
		self.panel.dialogType = self.dialogType
		return self.panel
	
	def parentLayerChanged(self, layer=None):
		pass
	
	def setLayer(self, layer):
		pass
	
	def setValue(self, value):
		pass
	
	def value (self):
		return self.panel.getParameters()
		
	def postInitialize(self, wrappers):
		pass
		